### ISSUE TITLE
Clarification about some plots

### ISSUE THREAD

**Issue by danarte** [marcus1487/nanoraw#26]
Disclaimer: some of the questions might be due to my inexperience with NGS and nanopre data in particular, if so please refer me to the relevant resource and I will happily learn the knowledge I'm missing.

Questions about the plots
plot_kmer - If I understand correctly it plots the kmer (trimer by default) frequency. What is the scale of Y axis?
 is it plotting the frequency in the reads? so trimers with bigger than 0 value appear more (than they would appear if all trimers had same frequency) and the trimers below 0 appear less?
Or is it frequencies compared to the reference genome?
Also why are the kmers colored/grouped by the last letter in the trimer? (in my results the groups were indeed ordered by the last letter in the trimer but I don't understand what is special about this last letter)

plot_correction - some minor clarifications; what are the black lines for? From the results I noticed the black lines come mark places where there is a "dramatic" change in signal, is there any explanation for this change? 

cluster_signif - this option seems unsupported, there is an error if I try to call it :"nanoraw: error: invalid choice: 'cluster_signif'"
same for plot_multi_correction...

Thank you for developing this package and publishing it.

**Comment by marcus1487** [comment]
For the plot_kmer command, the y-axis is the normalized electric current level at that k-mer (default to every position in all reads or average over whole reads with --read-mean option). The default normalization in the genome_resquiggle command is median, but ONT (pA) or raw (original digital readouts) are available as well. You can also store multiple normalization types in the same FAST5 files with alternative --corrected-group name for another normalization. The last letter is highlighted by the color as the dominant signal is the purine pyrimidine at the center of the pore. I should add an option to allow the k-mer to include up- and down-stream bases instead of only upstream. I will open an issue for this.

For the plot correction command, the black lines indicate basecall segmentation points (generally a new base causes a dramatic shift in the raw signal). Lines on the top of the plot are original basecalls (as specified by the --basecall-group option) and the bottom lines are segments after resolving with a genomic alignment (so they represent genomic bases). Red lines indicate segments that correspond to inserted or deleted bases (note that additional segments may be altered as well).

I am hoping to get to a tutorial shortly that will help to explain all of the functionalities, but hopefully this helps for now.

cluster_signif is a typo in the README. The `nanoraw -h` command gives the correct command names. cluster_signif should be cluster_most_significant. I don't see the same issue with plot_multi_correction. Let me know if you still have an issue with this command.
