### ISSUE TITLE
Extracting fasta/fastq from corrected reads?

### ISSUE THREAD

**Issue by danarte** [marcus1487/nanoraw#28]
Hello,
Is there a simple way to extract fasta/fastq files with the corrected data after we run genome_resquiggle on some reads files? (I examined the .fast5 files with HDF viewer after resquiggle and didn't see anything useful, I saw the aligned read sequence but I'm not sure how to extract it to a usable fasta/fastq)

**Comment by marcus1487** [comment]
I do not have a subcommand to output fasta/fastq from corrected reads, mostly because I am not sure if there is much value. The read sequence will by definition match the genome perfectly (as the correction is made specifically to match signal to genomic bases), so I am not sure what value a fasta with this information would provide.

In order to produce a fastq I would need some idea of probability/confidence in a base call, but there is no model here. Thus I don't forsee a fastq output at the moment.

If you did want to get the genomic bases each read is assigned you can extract those from the 'base' slot of the 'Events' data set. Here is an example to extract the template corrected (genomic) sequence from a fast5 file:
`import h5py
fast5_data = h5py.File(fast5_file)
''.join(fast5_data['/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events']['base'])`

I am closing this issue, but please let me know if there is a use case that requires a fasta/q and I would be happy to re-open the issue.
