### ISSUE TITLE
Nanoraw error 

### ISSUE THREAD

**Issue by Subhi** [marcus1487/nanoraw#38]
Hi, 

I am trying to analyze my 1D nanopore data using nanoraw.

However the nanoraw genome_resquiggle command using bwa, it makes a failed.txt and gives us an error :"No events or corrupted events in file. Likely a segmentation error or mis-specified basecall-subgroups (--2d?)"
Also, when I try to use plot_correction It gives me an error "Fewer reads than requested able to be processed.Likely few reads provided or not corrected"
Can someone help me to understand what is the problem?
Thanks
Serena

**Comment by marcus1487** [comment]
Hi Serena,

Thank you for logging your issue here. Any plotting command will fail if the genome_resquiggle command fails, so the second error should be fixed if we can fix the first. 

For the genome_resquiggle error, most likely there is something missing or misplaced in your FAST5 files. Are you using the default `--basecall-group` and `--basecall-subgroups` options? If you are using the defaults then ensure that the following slot exists in your FAST5 files: `/Analyses/Basecall_1D_000/BaseCalled_template/Events`. If you are not using those defaults, then replace `Basecall_1D_000` and `BaseCalled_template` appropriately. nanoraw has to know where basecalled events are located in order to begin processing so that seems to be your issue here. Let me know what you find!

I believe the most recent iteration of the ONT basecaller defaults to not storing these events anymore, so you may unfortunately have to re-run basecalling with this option set. If this is becoming an issue for users I will add this disclaimer to the help documents, etc.

P.S. You can use a tool such as [HDFView](https://support.hdfgroup.org/products/java/release/download.html) to view these slots in your FAST5 files.

**Comment by Subhi** [comment]
![hdfview](https://cloud.githubusercontent.com/assets/5695769/25486886/83b760fc-2b30-11e7-97df-15c2ea44ce7e.jpg)


Hi, thanks for your reply. Actually this is what HDF view looks like, there are no events stored. We used the local basecalling with the latest version of MinKNOW.
How can we re-run the basecalling (should we run the sample again?)

**Comment by marcus1487** [comment]
Indeed it looks as though the most current standard Minknow workflow may have removed the storing of Events data (required for nanoraw). I have not had a chance to dig into how to enable this within the workflow. I think albacore still stores events, so I would give that a try (maybe test a couple reads and check for events first). With the output/workflow changing I will try to stay up-to-date with these changes and make suggestions on the documentation as soon as I have a  chance to dig in. Thanks!

**Comment by Subhi** [comment]
Thanks

**Comment by marcus1487** [comment]
So it looks like minknow has shifted to not storing events as a default. This can be set by ticking the option on the minknow GUI in the future, but for now the FAST5s can be re-basecalled with albacore which still includes events by default. Just make sure to point nanoraw to the correct basecalling group within the fast5. This should be 'Basecall_1D_001' by default.
