### ISSUE TITLE
Nanoraw ignores moves longer than one

### ISSUE THREAD

**Issue by rasto2211** [marcus1487/nanoraw#50]
I've noticed that nanoraw ignores moves longer than one. So for example when you move from ACATG to ATGCC you get move=2 in the events table (dataset) in fast5 file (`/Analyses/Basecall_1D_000/BaseCalled_template/Events`). As I can see in the `get_read_data()` function, nanoraw only handles situations when move=0 (`fix_stay_states()`) and move=1. Why does nanoraw ignore the cases when move>1? Is this intentional or is it a actual bug? If it's intentional the it would be notice if you could leave a comment about this in the code. Right now, I don't see a reason to ignore moves longer than one.

Fast5 files also store fastq files in `/Analyses/Basecall_1D_000/BaseCalled_template/Fastq` with the full basecalled sequence. The algorithm that constructs this fastq file does not ignore moves longer than one. Why did you decide not to use this sequence?

Thank you for your response in advance.

**Comment by marcus1487** [comment]
In short this is intentional and not a bug. 

For the first point, the get_read_data() function returns a one to one matching of base sequence to event locations. I see two options to fix this. First in a move state >1 the event could be re-segmented immediately (but that runs into a lot of edge cases e.g. small events). The other option I see is to store the extra bases and resolve the extra base at the alignment stage as if it were an insertion into the segments required. Both options seem a bit hacky since in the end the genomic sequence is taken and thus these only effect the sequence going into the mapping. Hence I chose to take the first base from each event with move>0. 

For the second comment, the fastq stored in the fast5 does not store any assignment of the raw signal to that sequence. Thus the assignment would have to be learned essentially from scratch or with some alignment with the events. Either way this is quite a complex algorithm. 

As you can probably tell, this repo is not being actively maintained at this time, so I probably won’t add a comment to the code at this time. Look forward to updates soon... but not here;)

**Comment by rasto2211** [comment]
Thank you for the explanation.

**Comment by marcus1487** [comment]
I wanted to follow up on my ambiguous previous comment to note that a derivative work ([tombo](https://github.com/nanoporetech/tombo)) has just been released and will be supported to some limited extent moving forward. This software adds many features to the nanoraw framework, including addressing some of the issues brought up here.

**Comment by rasto2211** [comment]
Btw. how did you handle reads with `move > 1` in [this paper](https://www.biorxiv.org/content/early/2017/04/10/094672) ? Did you discard all the reads with `move > 1`?

**Comment by marcus1487** [comment]
No, the reads with one or more events with a move states > 1 do not need to be discarded at all. I think there is a misunderstanding of what is happening with move > 1.  With a move state of 1, the event is assigned exact that one base. With move > 1, I am simply ignoring the bases beyond the first new base introduced in each event. With move == 0, that event is merged with the previous event (as there is no base assigned to that event). This is simply creating a mapping between the events and base calls. Move states > 1 indicate that there is an event assigned more than one base. This requires either a re-segmentation of that event (where many edge cases quickly arise), or the extra bases are erroneous. Either way it seems as though pushing this problem downstream to the genomic alignment resolving state (re-squiggling if you would) was the right decision. If there are too many move states > 1 so that the read would not map to the genome I figured that this was likely going to be a poor read anyways. I am sure there are examples where this breaks down (especially with development base callers; metrichor/albacore tend to over segment which causes fewer move>1 states), but it seemed to perform well on a variety of dataset I tested. I hope this helps!

**Comment by rasto2211** [comment]
Ok, so you are basically saying that ignoring moves longer than one is an implicit filtering strategy for getting rid of low quality reads. Am I right? If the k-mer skip are not so common in the read then genome mapper (BWA-MEM / minimap2) can correct the error which was done by skipping the base.

**Comment by marcus1487** [comment]
I guess in effect it is a filter for a particular form of low quality reads, but that is certainly not its intended purpose. Mostly it would take a significant amount of effort to allow an event to be represented by more than one base, both in FAST5 processing and downstream in the re-squiggle algorithm section. Given that this is likely to only happen in low quality reads, it seemed like a low priority edge case to handle. I hope that helps.

**Comment by rasto2211** [comment]
Thanks.
